name: Demo Duke

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
      - name: 'Set up Java Development Kit'
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: 'Set up Duke.java'
        run: echo -e "/open https://src.duke.run/Duke.java\n/save Duke.java\nDuke.status()" | jshell -
      - name: 'Show version of tool: jar'
        run: java Duke.java jar --version
      - name: 'Show Duke Status'
        run: java Duke.java /status
